#ifndef __PHRASE_HPP__
#define __PHRASE_HPP__

enum class Phrase {
    CB_AT_1ST_DIRECTORY,
    CF_AT_LAST_DIRECTORY,
    CHANGE_DIRECTORY_FAIL,
    CHANGE_TO,
    CLEARED_NOTIFICATION,
    CURRENT_DIRECTORY,
    HELLO_WORLD,
    INVALID_CTLMODE_ARG,
    INVALID_FILE_FORMAT,
    INVALID_NUMBER,
    INVALID_SOURCE,
    MISSING_OPERAND,
    OPEN_FILE_FAIL,
    OUT_OF_RANGE,
    USE_NULL_PTR,
    UNKNOWN
};

using phrz = Phrase;

#endif
